name: walletflow
description: "Personal Finance - Expense, Budget and Loan Tracking App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State Management
  get: ^4.6.6
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Cloud Database & Auth
  supabase_flutter: ^2.5.4
  google_sign_in: ^6.2.2
  
  # Charts
  fl_chart: ^0.69.0
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0
  csv: ^6.0.0
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  
  # Environment
  flutter_dotenv: ^5.2.1
  
  # HTTP
  dio: ^5.7.0
  
  # Connectivity
  connectivity_plus: ^6.1.0
  google_fonts: ^8.0.2
  dynamic_color: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - .env
