// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDxLVdyTVuxFzYWDrnHbVWWZa0iumbau0',
    appId: '1:708904354047:web:d92ff3da1620353c37ccca',
    messagingSenderId: '708904354047',
    projectId: 'walletflow-1d9c1',
    authDomain: 'walletflow-1d9c1.firebaseapp.com',
    storageBucket: 'walletflow-1d9c1.firebasestorage.app',
    measurementId: 'G-KJ7QY8SYP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiB6ObWWdxKvIt1LLFV8ZcCufr9JE8ZDc',
    appId: '1:731118662529:android:b0a13af6ff50cf242fae80',
    messagingSenderId: '731118662529',
    projectId: 'walletflow-7488',
    storageBucket: 'walletflow-7488.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2mxwBM2ZlA8tzFYtjlzW4maiV-hK3akQ',
    appId: '1:708904354047:ios:1185ac3a3f37abe337ccca',
    messagingSenderId: '708904354047',
    projectId: 'walletflow-1d9c1',
    storageBucket: 'walletflow-1d9c1.firebasestorage.app',
    iosBundleId: 'com.walletflow.walletflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2mxwBM2ZlA8tzFYtjlzW4maiV-hK3akQ',
    appId: '1:708904354047:ios:1185ac3a3f37abe337ccca',
    messagingSenderId: '708904354047',
    projectId: 'walletflow-1d9c1',
    storageBucket: 'walletflow-1d9c1.firebasestorage.app',
    iosBundleId: 'com.walletflow.walletflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDxLVdyTVuxFzYWDrnHbVWWZa0iumbau0',
    appId: '1:708904354047:web:b66a643c7dafa32337ccca',
    messagingSenderId: '708904354047',
    projectId: 'walletflow-1d9c1',
    authDomain: 'walletflow-1d9c1.firebaseapp.com',
    storageBucket: 'walletflow-1d9c1.firebasestorage.app',
    measurementId: 'G-2NDGSV84W0',
  );
}